<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <CiToolsTargetFramework Condition="'$(CiToolsTargetFramework)' == ''">net9.0</CiToolsTargetFramework>
        <TargetFramework>$(CiToolsTargetFramework)</TargetFramework>
        <PublishSingleFile>true</PublishSingleFile>
        <PublishSelfContained>true</PublishSelfContained>
        <DebugType>none</DebugType>
        <ImplicitUsings>disable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AssemblyName>steamcmd</AssemblyName>
        <RootNamespace>CiTools.SteamCmd</RootNamespace>
    </PropertyGroup>
</Project>
