<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <CiToolsTargetFramework Condition="'$(CiToolsTargetFramework)' == ''">net9.0</CiToolsTargetFramework>
        <TargetFramework>$(CiToolsTargetFramework)</TargetFramework>
        <PublishSingleFile>true</PublishSingleFile>
        <SelfContained>false</SelfContained>
        <DebugType>none</DebugType>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
        <AssemblyName>ci-tools-launcher</AssemblyName>
    </PropertyGroup>
    <ItemGroup>
        <Compile Include="*.cs" />
    </ItemGroup>
    <ItemGroup>
        <InternalsVisibleTo Include="CiTools.Tests" />
    </ItemGroup>
</Project>
